name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: low
          deny-licenses: |
            GPL-2.0-only
            GPL-2.0-or-later
            GPL-3.0-only
            GPL-3.0-or-later
            AGPL-3.0-only
            AGPL-3.0-or-later
            LGPL-2.1-only
            LGPL-2.1-or-later
            LGPL-3.0-only
            LGPL-3.0-or-later
            EPL-1.0
            EPL-2.0
          allow-ghsas: |
            GHSA-pxg6-pf52-xh8x
